dependencies:
  - python=3.8
  - pip=21.1.1
  - pip:
    # Protobuf is needed to avoid conflict with managed spark
    - protobuf==3.19.6
    # Feature store core SDK
    - https://featurestoreprp.blob.core.windows.net/prp/feature-source/azure_ai_ml-1.9.0-py3-none-any.whl
    - https://featurestoreprp.blob.core.windows.net/prp/feature-source/azureml_featurestore-0.0.1-py3-none-any.whl
    # This is needed if you want to execute the Part 2 of the "SDK" track or execute "SDK+CLI" track in the docs tutorial
    - azure-cli    

    # Following are required for training and batch inference pipeline of *this* sample. Users can remove this for their own projects
    - scikit-learn
    - pandas
name: fs_env
