name: custom_transformers_deploy
channels:
- conda-forge
- anaconda
- pytorch
- nvidia
dependencies:
- python=3.8
- pip=21.2.4
- pytorch=1.13.1
- pytorch-cuda=11.7
- pip:
  - protobuf<4.0.0
  - psutil>=5.8,<5.9
  - pandas>=1.1,<1.2
  - transformers==4.28.1
  - sentencepiece==0.1.97

