
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
   builder: html
   configuration: sdk/python/docs/conf.py

python:
   install:
   - requirements: requirements-doc.txt

formats:
  - epub
  - pdf
