name: mir-deploy
type: online
auth_mode: aml_token
traffic:
    blue: 100
deployments:
    -   name: blue
        model:
           name: bert
           version: 1
           local_path: ./models
        code_configuration:
            code:
                local_path: ./code
            scoring_script: dummy.py
        environment:
            name: triton-mir-endpoint
            version: 1
            docker:
                image: mcr.microsoft.com/azureml/tritonserver-21.02-py38-inference:20210525.1
        environment_variables:
            ORT_TENSORRT_FP16_ENABLE: 1
        request_settings:
            max_concurrent_requests_per_instance: 512
        scale_settings:
            scale_type: manual
            instance_count: 1
        instance_type: Standard_NC6s_v3
