$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: pipeline_with_import_export_data
description: pipeline job import export data to azure sql
settings:
    default_compute: azureml:cpu-cluster
    force_rerun: true

inputs:
  data_file:
    type: mltable
    path: ./local-mltable
  connection_target_azuresql: azureml:my_azuresql_connection
  query_source: SELECT * FROM sample_data
jobs:
  export_csv_to_database:
    type: data_transfer
    task: export_data
    inputs:
      source: ${{parent.inputs.data_file}}
    sink: 
        type: database
        table_name: sample_data
        connection: ${{parent.inputs.connection_target_azuresql}}
  import_table:
    type: data_transfer
    task: import_data    
    source: 
      type: database
      query: ${{parent.inputs.query_source}}
      connection: azureml:my_azuresql_connection
    outputs:
      sink: 
        type: mltable   
