channels:
- defaults
- conda-forge
dependencies:
- python=3.6.8
- pip=20.0
- pip:
  - azureml-sdk==0.1.0.*
  - --index-url https://azuremlsdktestpypi.azureedge.net/dev/aml/office/134157926D8F
  - --extra-index-url https://pypi.org/simple
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/modulesdkpreview
  - azure-ml-component==0.1.0.*
  - git+https://github.com/NVIDIA/dllogger.git@26a0f8f1958de2c0c460925ff6102a4d2486d6cc#egg=dllogger
  - watchdog==0.10.3
  - torch==1.8.1
  - torchvision==0.9.1
  - tensorboard==2.5.0
  - pillow==8.2.0
  - numpy==1.19.5
  - --extra-index-url=https://developer.download.nvidia.com/compute/redist/
  - nvidia-dali-cuda100
name: project_environment