name: blue
endpoint_name: my-endpoint
model:
  local_path: ../../model-1/model/sklearn_regression_model.pkl
code_configuration:
  code: 
    local_path: ../../model-1/onlinescoring/
  scoring_script: score.py
environment: 
  path: .
  conda_file: file:../../model-1/environment/conda.yml
  docker:
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210727.v1
instance_type: Standard_F2s_v2
scale_settings:
  scale_type: manual
  instance_count: 1
  min_instances: 1
  max_instances: 2
