channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.9
  - pip=20.2.4
  - pip:
      - >-
        --extra-index-url
        https://dataprepdownloads.azureedge.net/pypi/test-M3ME5B1GMEM3SW0W/58645529
      - >-
        --extra-index-url
        https://azuremlsdktestpypi.azureedge.net/AzureML-Train-AutoML-Validation/58802184
      - azureml-core==0.1.0.58802184
      - azureml-mlflow==0.1.0.58802184
      - azureml-pipeline-core==0.1.0.58802184
      - azureml-telemetry==0.1.0.58802184
      - azureml-interpret==0.1.0.58802184
      - azureml-responsibleai==0.1.0.58802184
      - azureml-automl-core==0.1.0.58802184
      - azureml-automl-runtime==0.1.0.58802184
      - azureml-train-automl-client==0.1.0.58802184
      - azureml-train-automl-runtime==0.1.0.58802184
      - azureml-dataset-runtime==0.1.0.58802184
      - azureml-defaults==0.1.0.58802184
      - azureml-dataprep-native==38.0.0
      - azureml-dataprep-rslex==2.4.0.dev0+805cf9f
      - inference-schema
      - py-cpuinfo==5.0.0
      - mpi4py==3.1.3
      - click<8.0.0
      - pystan==2.19.1.1
      - boto3==1.15.18
      - botocore==1.18.18
      - joblib==0.14.1
      - cloudpickle==1.6.0
      - azureml-dataprep==2.28.0.dev0+805cf9f
  - numpy~=1.18.0
  - scikit-learn==0.22.1
  - pandas~=1.1.5
  - py-xgboost==1.3.3
  - fbprophet==0.7.1
  - holidays==0.10.3
  - setuptools-git
  - 'psutil>5.0.0,<6.0.0'
name: azureml_d7e16e69ed2a51d0630540e4b8fe1147