dependencies:
  - python=3.8
  - pip:
      - protobuf==3.19.6
      - mlflow-skinny
      - 'azureml-featurestore[online]==0.1.0b1'
      - aiohttp==3.8.4
      - azureml-inference-server-http
      - scikit-learn
      - pandas
      - azure-identity
name: fs_env